# Usage: docker-compose run --name tmkit-dev tmkit
version: '3'
services:
  tmkit-arm64:
    image: "2003100127/tmkit:v0.0.2.1"
    platform: linux/arm64
    volumes:
      - ./:/workspace

  tmkit:
    image: "2003100127/tmkit:v0.0.2.1"
    platform: linux/amd64
    volumes:
      - ./:/workspace
