package:
  name: "tmkit"
  version: "0.0.5"

source:
  path: "../"

build:
  number: 0
  entry_points:
    - tmkit=tmkit.__main__:main
  script: "pip install . --ignore-installed -vvv"

requirements:
  host:
    - python=3.10
    - poetry
  run:
    - python=3.10
    - hhsuite
    - pymol-open-source
    - hmmer

about:
  home: "https://github.com/2003100127/tmkit"
  license: GPL-3.0
  license_family: GPL
  summary: "A toolkit for transmembrane protein structure prediction."
  doc_url: "https://tmkit-guide.herokuapp.com/doc/overview"
  dev_url: "https://github.com/2003100127/tmkit"
