name: publish_conda

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.11  # ✅ Force Python 3.11 (Biopython 1.79 does NOT support 3.12)
          channels: conda-forge,bioconda

      - name: Install Conda Build Tools
        run: |
          conda install -y conda-build conda-verify

      - name: Build Conda Package
        run: |
          conda build -c conda-forge -c bioconda -c jianfeng_sun --output-folder conda conda/

      - name: Verify Built Package
        run: |
          echo "Checking built packages..."
          ls -lah conda/linux-64/ || echo "No package found!"  # ✅ Check if the package exists

      - name: Convert Package for Other Platforms
        run: |
          if ls conda/linux-64/*.tar.bz2 1> /dev/null 2>&1; then  # ✅ Only convert if package exists
            mkdir -p conda/osx-64 conda/win-64
            conda convert -p osx-64 conda/linux-64/*.tar.bz2 -o conda/
            conda convert -p win-64 conda/linux-64/*.tar.bz2 -o conda/
          else
            echo "No package found, skipping conversion."
            exit 1
          fi

      - name: Publish to Conda
        uses: 2003100127/conda-publish-action@master
        with:
          subdir: 'conda'
          anacondatoken: ${{ secrets.ANACONDA_TOKEN }}
          platforms: 'win osx linux'
