name: testpypi-publish

on:
  push:
    tags:
      - "zzz*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.17
        with:
          python_version: "3.10"
          poetry_version: "==1.5.1" # (PIP version specifier syntax)
          pypi_token: ${{ secrets.PYPI_TOKEN_TEST }}
          build_format: "sdist"
          allow_poetry_pre_release: "yes"
          ignore_dev_requirements: "yes"
          repository_name: "testpypi"
          repository_url: "https://test.pypi.org/legacy/"
